-- MySQL Script generated by MySQL Workbench
-- 10/01/16 13:42:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema finance_tracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema finance_tracker
-- -----------------------------------------------------
DROP SCHEMA finance_tracker;
CREATE SCHEMA IF NOT EXISTS `finance_tracker` DEFAULT CHARACTER SET utf8 ;
USE `finance_tracker` ;

-- -----------------------------------------------------
-- Table `finance_tracker`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finance_tracker`.`users` (
  `user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `password` CHAR(32) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `finance_tracker`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finance_tracker`.`accounts` (
  `account_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_user_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `balance` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `institution` VARCHAR(50) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `fk_currency_id` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `fk_accounts_id_users_idx` (`fk_user_id` ASC),
  INDEX `fk_accounts_currency_id_idx` (`fk_currency_id` ASC),
  CONSTRAINT `fk_accounts_users_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `finance_tracker`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `finance_tracker`.`accounts_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finance_tracker`.`accounts_log` (
  `accounts_log_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_user_id` INT(10) UNSIGNED NOT NULL,
  `fk_account_id` INT(11) UNSIGNED NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `time_stamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`accounts_log_id`),
  INDEX `fk_acc_user_id_idx` (`fk_user_id` ASC),
  INDEX `fk_acc_log_acc_id` (`fk_account_id` ASC),
  CONSTRAINT `fk_acc_log_account_id`
    FOREIGN KEY (`fk_account_id`)
    REFERENCES `finance_tracker`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acc_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `finance_tracker`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `finance_tracker`.`currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finance_tracker`.`currencies` (
  `currency_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(4) NOT NULL,
  `long_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`currency_id`, `short_name`),
  UNIQUE INDEX `currency_id_UNIQUE` (`currency_id` ASC),
  UNIQUE INDEX `short_name_UNIQUE` (`short_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `finance_tracker`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finance_tracker`.`tags` (
  `tag_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `fk_parent_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fk_user_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC),
  INDEX `fk_tag_parent_id_idx` (`fk_parent_id` ASC),
  INDEX `fk_tag_user_id` (`fk_user_id` ASC),
  CONSTRAINT `fk_tags_parent_id`
    FOREIGN KEY (`fk_parent_id`)
    REFERENCES `finance_tracker`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `finance_tracker`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `finance_tracker`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finance_tracker`.`transactions` (
  `transaction_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_user_id` INT(10) UNSIGNED NOT NULL,
  `ft_account_id` INT(10) UNSIGNED NOT NULL,
  `fk_tag_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `description` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `date` DATE NULL DEFAULT NULL,
  `file` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `step` INT(11) NULL DEFAULT '0',
  `transaction_repeat` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `idtransactions_UNIQUE` (`transaction_id` ASC),
  INDEX `fk_transactions_user_id_idx` (`fk_user_id` ASC),
  INDEX `fk_transactions_account_id_idx` (`ft_account_id` ASC),
  INDEX `fk_transaction_tag_id_idx` (`fk_tag_id` ASC),
  CONSTRAINT `fk_transaction_tag_id`
    FOREIGN KEY (`fk_tag_id`)
    REFERENCES `finance_tracker`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_account_id`
    FOREIGN KEY (`ft_account_id`)
    REFERENCES `finance_tracker`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `finance_tracker`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `finance_tracker`.`users_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finance_tracker`.`users_log` (
  `login_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_user_id` INT(10) UNSIGNED NOT NULL,
  `time_stamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`login_id`),
  INDEX `fk_logins_user_id_idx` (`fk_user_id` ASC),
  INDEX `timestamp_idx` (`time_stamp` ASC),
  CONSTRAINT `fk_logins_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `finance_tracker`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;